name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download 469b Patch
        uses: robinraju/release-downloader@v1.2
        with:
          repository: "OldUnreal/UnrealTournamentPatches"
          tag: "v469b"
          fileName: "OldUnreal-UTPatch469b-Windows.zip"
          
      - name: Extract Patch
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: "OldUnreal-UTPatch469b-Windows.zip"
          pathTarget: .

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}/

      - name: Extract Necessary Resources
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{ github.event.repository.name }}/Build/BuildEnv.zip
          pathTarget: .

      - name: Build ${{ github.event.repository.name }}
        run: ${{ github.event.repository.name }}/build.bat silent noint

      - name: Save UCC.log
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: ucc-output
          path: System/UCC.log

      - name: Save ${{ github.event.repository.name }} Package
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ github.event.repository.name }}/System/
            ${{ github.event.repository.name }}/LICENSE
            ${{ github.event.repository.name }}/README.md
