name: Release

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download 469b Patch
        uses: robinraju/release-downloader@v1.2
        with:
          repository: "OldUnreal/UnrealTournamentPatches"
          tag: "v469b"
          fileName: "OldUnreal-UTPatch469b-Windows.zip"
          
      - name: Extract Patch
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: "OldUnreal-UTPatch469b-Windows.zip"
          pathTarget: .

      - name: Determine Release Package Name
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo ("PKG_NAME=${{ github.event.repository.name }}_${{ github.event.release.tag_name }}") >> $env:GITHUB_ENV

      - name: Determine Package Name
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: echo ("PKG_NAME=${{ github.event.repository.name }}") >> $env:GITHUB_ENV

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
        with:
          path: ${{ env.PKG_NAME }}/

      - name: Extract Necessary Resources
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{ env.PKG_NAME }}/Build/BuildEnv.zip
          pathTarget: .

      - name: Build ${{ github.event.repository.name }}
        run: ${{ env.PKG_NAME }}/build.bat silent noint

      - name: Save UCC.log
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: ucc-output
          path: System/UCC.log

      - name: Save ${{ github.event.repository.name }} Package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PKG_NAME }}
          path: |
            ${{ env.PKG_NAME }}/System/
            ${{ env.PKG_NAME }}/LICENSE
            ${{ env.PKG_NAME }}/README.md

      - name: Create Release Asset
        run: >
          7z a -tzip -- ${{ env.PKG_NAME }}.zip
          ${{ env.PKG_NAME }}/System/
          ${{ env.PKG_NAME }}/LICENSE
          ${{ env.PKG_NAME }}/README.md

      - name: Attach Asset To Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.PKG_NAME }}.zip
          overwrite: true
