name: CI

on:
  push:

  pull_request:

  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download 469b Patch
        uses: robinraju/release-downloader@v1.2
        with:
          repository: "OldUnreal/UnrealTournamentPatches"
          tag: "v469b"
          fileName: "OldUnreal-UTPatch469b-Windows.zip"
          
      - name: Extract Patch
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: "OldUnreal-UTPatch469b-Windows.zip"
          pathTarget: .

      # - run: |
      #     echo ("${{ toJSON(env) }}")
      #     echo ("${{ toJSON(github) }}")

      - name: Determine Package Name
        run: |
          if ("${{ github.ref_type }}" -eq "tag") {
            echo ("PKG_NAME=${{ github.event.repository.name }}_"+"${{ github.ref }}".SubString(10)) >> $env:GITHUB_ENV
          } elseif ("${{ github.ref }}".StartsWith("refs/pull/:")) {
            echo ("PKG_NAME=${{ github.event.repository.name }}_pr_"+"${{ github.ref }}".SubString(11, $length - 17)) >> $env:GITHUB_ENV
          } else {
            echo ("PKG_NAME=${{ github.event.repository.name }}_"+"${{ github.ref }}".SubString(11)+"-"+"${{ github.sha }}".SubString(0,8)) >> $env:GITHUB_ENV
          }

      - name: Save Package Name In File
        run: echo ("${{ env.PKG_NAME }}") >> PackageName

      - name: Create Package Name Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PackageName
          path: PackageName
          retention-days: 1
          if-no-files-found: error

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
        with:
          path: ${{ env.PKG_NAME }}/

      - name: Extract Necessary Resources
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{ env.PKG_NAME }}/Build/BuildEnv.zip
          pathTarget: .

      - name: Build ${{ github.event.repository.name }}
        run: ${{ env.PKG_NAME }}/build.bat silent noint

      - name: Save UCC.log
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: ucc-output
          path: System/UCC.log

      - name: Save ${{ github.event.repository.name }} Package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PKG_NAME }}
          path: |
            ${{ env.PKG_NAME }}/System/
            ${{ env.PKG_NAME }}/Docs/
            ${{ env.PKG_NAME }}/LICENSE
            ${{ env.PKG_NAME }}/README.md

  release:
    runs-on: windows-latest
    needs: build
    if: ${{ github.event_name == 'release' }}

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: PackageName

      - name: Restore Package Name
        run: |
          echo ("PKG_NAME=" + (Get-Content -Path "PackageName")) >> $env:GITHUB_ENV

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.PKG_NAME }}

      - name: Create Release Asset
        run: >
          7z a -tzip -- "../${{ env.PKG_NAME }}.zip"
          System/
          Docs/
          LICENSE
          README.md

      - name: Attach Asset To Release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.PKG_NAME }}.zip
          overwrite: true

